version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"

  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    command: sync
    restart: unless-stopped
    volumes:
      - /home/mediaserver/.custom/plextraktsync/config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

  plextraktwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktwatch
    command: watch
    restart: unless-stopped
    volumes:
      - /home/mediaserver/.custom/plextraktsync/config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

